# Generated by Django 5.1.1 on 2024-10-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
