# Generated by Django 5.1.4 on 2024-12-14 21:39

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=orders.models.generate_order_id, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
